### ISSUE TITLE
Tags and Manifest mismatch

### ISSUE THREAD

**Issue by ghost** [frrahat/Quran-For-My-Android#1]
A version 1.0.1 has been tagged, but the versionCode and versionName in AndroidManifest.xml are still at "1.0" and "1". At least the versionCode should always be updated, since this is the value that gets tested on updatechecks.

**Comment by ghost** [comment]
Thanks for the quick response, however 

```
android:versionCode="1.0.2"
android:versionName="1.0" >
```

should be something like

```
android:versionCode="1.0.2"
android:versionName="102" >
```

The versionCode is a simple integer value. It's common practice to mimic the version name, but actually it doesn't matter as long as the new VC is higher than the last version. Have a look at https://developer.android.com/tools/publishing/versioning.html for further reference.

**Comment by frrahat** [comment]
Thanks a lot for your help. I will update the manifest file.
