### ISSUE TITLE
[Feature Request] translation

### ISSUE THREAD

**Issue by HassanHeydariNasab** [frrahat/Quran-For-My-Android#11]
Assalmualaykum brother
Please add a feature for who want to tranlate Quran to their languages .
and exporting like Zekr's translations files for globally use .
Thanks

**Comment by frrahat** [comment]
Wa 'Alaykumussalam Wa Rahmatullah.
I am sorry brother. Making a translation of the Quran is a very risky issue, as there are possibilities of facing the wrath of Allah for making wrong translation of the Quran. We should hand it to the people who have much knowledge in Arabic language, Arabic grammar, tafsir , hadis etc. Or, we should follow a well-known book with authentic translation. In both cases, a well formed Text Editor is required.

But my app aims to provide quick access or sharing of the ayahs of Quran, so in this respect, adding an extra text editor for translating verses is really unimportant.
