### ISSUE TITLE
Remove Tahoma

### ISSUE THREAD

**Issue by ebraminio** [frrahat/Quran-For-My-Android#13]
Hi. Thanks for the app. Please don't ship Tahoma with the app. Tahoma is copyright protected font https://www.myfonts.com/fonts/microsoft/tahoma/licensing.htm

Also please remove other non-free fonts, you can find better and free ones from https://fontlibrary.org like https://fontlibrary.org/en/font/amiri

**Comment by frrahat** [comment]
Thanks for the info. I will check other fonts insha Allah.
If you find any other font used in this project is in question, please let me know.
I will update those in the next release insha Allah.

**Comment by ebraminio** [comment]
I guess other than Droid Naskh, others are non-free probably and should be removed but other than copright issue, there are already good free fonts needs to be encouraged, http://old.arabeyes.org/project.php?proj=Khotot
We can also ask from @khaledhosny about more free fonts for a free Quran application, he knows and maintains many free fonts.

**Comment by frrahat** [comment]
Zajakallahu khairan brother, for your help.
Insha Allah in the next release I will clear the issue.

**Comment by frrahat** [comment]
Assalamu 'Alaikum brother.
Sorry for being so late to handle the issue. Actually I was searching for a font to render Arabic perfectly with diacritics in my Android 4.2.2 to complete the next release to come.
By the way, I have removed tahoma.ttf. And indeed, I have found a very good font in the repository of   [khaledhosny](https://github.com/khaledhosny) and included in this app. Thanks a lot for the link.
Now I have added these fonts being sure that they are free to use:
"jaghb_uni_bold.ttf,
"amiri-quran.ttf",
"amiri-regular.ttf",
"droid_naskh_regular.ttf",
"me_quran.ttf",
"siyamrupali.ttf"

If you see anything wrong please be kind to inform me about that.

**Comment by ebraminio** [comment]
Thank you. Of course by "free" I meant the more strict sense as being free and open source licensed (that I guess jaghb_uni and me_quran aren't) but the top priority was Tahoma removal which is already done :)
