### ISSUE TITLE
Word by Word DB, new DBs, Tafsir

### ISSUE THREAD

**Issue by Sadmansamee** [frrahat/Quran-For-My-Android#17]
We have collected and organized Word By Word meaning for Bangla, English and Indonesian and we have gathered many other translation. Please checkout these repos

1. https://github.com/GreentechApps/Al-Quran
2. https://github.com/SadaqaWorks/Word-By-Word-Quran-Android
3. https://github.com/SadaqaWorks/IslamicDatabase

**Comment by frrahat** [comment]
Zajak Allahu Khairan
