### ISSUE TITLE
Does not start on Android Lollipop

### ISSUE THREAD

**Issue by MinaCora** [frrahat/Quran-For-My-Android#5]
I have two devices with Android Lollipop. One is with stock Motorola ROM and the other with CM12.

Unfortunately the app crashes on both devices after the first  screen (Primary Text Selection). 

As soon as I press done it says that the application was closed.

I hope you find a solution because I really love this app.

Furthermore I would appreciate to have also Turkish and German translations provided. 

Thanks for providing this fantastic app to humanity and may Allah take care of you!

**Comment by MinaCora** [comment]
The issue mentioned above only refers to version 1.1.

Version 1.0 works fine but as mentioned in an earlier issue by someone else does not provide the menu button to see the list of suras.

**Comment by frrahat** [comment]
Assalamu 'alaikum. Thanks for your comment. I am really happy to learn that this app was somewhat helpful for you. I will try to solve this issue and also try to add "additional language adding" feature, insha Allah.

**Comment by MinaCora** [comment]
Wa-Alaikum-Salaam my brother. I am looking forward that mankind will profit from your work. May Allah guide you. Alhamdulillah!

**Comment by mo3rfan** [comment]
Same issue I've been experiencing! I'm trying to sort it out on my builds too!

**Comment by frrahat** [comment]
Assalamu 'alaikum.
Please check this release. https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.2.0

Additional translation adding feature has been added in this new release. So, now it will be possible to add your desired translations.

I hope, this will not crash. Still, if any bug is found, please inform.

**Comment by MinaCora** [comment]
Wa-Alaikum-Salaam my brother!
Wonderful news!

I have installed version 1.2.0 and it works!
Thanks for your work!!!

I have made use of the "Additional Texts" feature and have updated one of the translations that was provided at the link, that was shown when opening the "Additional Texts" page. 
I have downloaded a zip-file - unzipped it and then added this one on the "Additional Texts" page. 
The implementation works wonderful. Thanks!

If you allow I would like to share my thoughts on how to improve the App further. 
In the "Additional Text" window the link is disappearing after having added one language file. 
Because I speak several other languages I prefer having those also in your App so I can check if the meaning of the translations is the same. 
After having added the first TXT-file the link disappeared - and I had no guidance how to upload more files. 

I have also faced a minor bug when rotating my phone by 90° (to landscape mode - or back). Whenever I do this during reading the Quran it says "Loading English Text" and then the prev/next buttons do not work anymore. The App says "No previous input".

Maybe one further thought. From usability point of view I would appreciate to get the "List of Suras" displayed as the start screen. Because I am typically starting there. With the menu button you have included in the upper right corner it is now possible for me to access also this list. That was not possible in V.1.0.0. 

Anyway these are only minor issues - and not of relevance. 
You have fixed the most important bug - and that was that it did not run in Android Lollipop - and this is resolved - and I can make use of it now. 
I propose you upload it on f-droid - so also others can make use of your work. 

Thank you - and may Allah protect you!

**Comment by frrahat** [comment]
All praises be to Allah, for the help to accomplish the work. May Allah, accept my work as good deed.

Thanks a lot. Jazakallahu Khairan for your comment.
Alhamdulillah, it is very refreshing to know that it worked on your device. 

In the 'Additional Texts' I have provided a link suggestion when there is no previously added file to a give a kick start to the new user. As it was just a "suggestion" I didn't continue all the way. However, this link is mentioned again in the "Help" option ( just above the Setting option). Insha Allah, as you suggested, I will continue the "link suggestion" in the new version.

It might be a helpful information. You have said that, you unzipped the downloaded .zip file, but it wasn't necessary. .zip file format is acceptable. So, you can simply choose a .zip file for additional text.

The rotating issue is certainly a big issue. When a rotation happens, all data are loaded again and the old information is lost. Insha Allah, I will try to solve this also.

As the List of Surahs can be accessed easily and quickly I don't think it is so much important to make this as the start screen. But as you suggested, an option can be added in the settings for this purpose.

Thanks for your propoal . but before you have proposed, the app is already in the F-droid (https://f-droid.org/packages/com.frrahat.quransimple/) , but I don't know who have uploaded it !  

And again, jazakallahu khairan.

**Comment by MinaCora** [comment]
Wa Antum fa Jazâkumu-Allâhu khayran.
Alhamdulillah my brother, sharing the words of god is good deed.
I am using your app to read the Qur'an to become a better servant of Allah. 
It makes me happy to see people like you, people with knowlegde, who use their abilities to help others in making this world a peaceful place. 
Salām!

**Comment by frrahat** [comment]
Assalamu 'Alaikum, brother/sister. Here is a new release :https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.3.0

Sorry for being so late.

As you have suggested, I have tried to add some changes.

Access to the 'link suggestion' from the "Additional Texts" screen has been enabled by creating a "Help" option at the top corner. In the "**_Additional Texts**_" category of the "Help" screen the "link suggestion" can be found again.

And for quick access to the Surah list, a quick button has been palced on the action bar of the home screen. I think it will be quicker or more comfortable than in the previous version.
![home screen v 1 3 0](https://cloud.githubusercontent.com/assets/7325483/7523952/89a2b25c-f520-11e4-9910-c4e4dc87d58b.png)

At last,  
Sorry, for the screen rotating issue. I think I should take more time. So, this bug has't been fixed yet.

Please inform, if you find more bugs.

**Comment by MinaCora** [comment]
Wa-Alaikum-Salaam my brother!

Thanks for making the Quran app better and better!

Btw: The new version is not yet available from the F-Droid repo  - only available by your link yet. 

May Allah take care of you!

**Comment by MinaCora** [comment]
Assalamu 'Alaikum my brother.

I have tested rel. 1.3. for a while and really like the button for the list of sura's!
This makes it easier for me to jump to the sura/verse I am looking for - because I am not using the manual entry. 
Maybe as an idea: 
Whenever the app is started you get confronted with a big black page without content - except the entry field on the top. 
Imagine a person who does not know anything about the Quran.
He just reads "enter verse number". 
Ok then he enters 1. 
Please see yourself what happens. 
The system shows "Invalid input". 
This person could think that either the app does not work - or that the usability concept is not supportive/self explaining. 
The button with the list of sura's is a great help for people who are first confronted with the app.
Just as an idea:
The app could be designed in that way that the "table of contents" are displayed on the first page when you open the app. Nevertheless the entry field can stay on top - for people who are searching a specific verse. 

Further not so important points - but maybe for the case you get the feeling that everyting is done and you need inspiration how to polish the app up.
- Splash Screen: I really like the icon of the app. As an idea you could scale it big and put it on a white background splash screen which is shown for one second on start up. 
- "Material" design (Android lollipo style) ... for future

May Allah give you energy and knowledge so that maximum possible number of humans Allah created may profit from your work. 

Allahu akbar!

**Comment by frrahat** [comment]
Walaikum Assalam Wa Rahmatullah.
Jazakallahu khairan for your interest to make this app better with your useful ideas.

Insha 'Allah,I wil try to implement those ideas. Actually, I am giving more importance to the functionality of the app and less to the design. Insha 'Allah if I find more time, I will try to use those in the design you have suggested.
