### ISSUE TITLE
[Feature Request] Custom font

### ISSUE THREAD

**Issue by HassanHeydariNasab** [frrahat/Quran-For-My-Android#8]
Please add option for user's font .
I think "Droid Naskh Arabic" is good for default .

**Comment by frrahat** [comment]
Jazakallhu khairan for this important information. Insha Allah, this and the other features you have mentioned will be considered in the next release.

**Comment by frrahat** [comment]
Assalamu alaikum, brother. Please, check this release : https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.3.0

**Comment by HassanHeydariNasab** [comment]
Thanks brother
selecting default fonts is working but when I selected another font, nothing added .

**Comment by frrahat** [comment]
Did you mean, same type of text in different font selection? If you can, please clarify what you have done, so that, it will help me to point out the bug.

**Comment by HassanHeydariNasab** [comment]
when I select "Add More Font Files" to choose a font (like EXAMPLE.ttf), no fonts add to 5 default fonts.
1.jaghub.....
2.tahoma
3.droid...
4.sol...
5.Default
6. NOTHING ADD TO THIS PLACE !

oh, if you store any data on SDcard, I haven't a writable of it. :D

**Comment by frrahat** [comment]
Yes, font data and the copy of the font is stored in the storage folder. Though, there are codes in the program to work on the devices where external storage (SD card) is unavailable, I haven't tested on such devices. 

As this is not working on your device, there are some missing in the code which need to be fixed.
Jazakallahu khairan for your clarification of the problem. Insha Allah, in the later release I will try to fix this problem and inform you about it.

**Comment by frrahat** [comment]
Assalamu 'alaikum,brother. I've tested the app in devices with the SD card unavailable, it works fine. I think, there is other thing causing this problem.

**Comment by HassanHeydariNasab** [comment]
My SD card exists but it is read-only.
I will buy a new one and test.

**Comment by frrahat** [comment]
I am updating a new release. Some little changes. It may work.

**Comment by frrahat** [comment]
Assalamu 'Alaikum.
Here is a new update: https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.3.1
I highly expect that it will solve the problem, but I am not sure. If you find time, please check this update.

**Comment by HassanHeydariNasab** [comment]
Now it's working very well !
Thanks a lot :)

**Comment by frrahat** [comment]
Alhamdulillah!
Thank you too for helping me find out the problem. :)
