### ISSUE TITLE
[Feature Request] Text selection

### ISSUE THREAD

**Issue by HassanHeydariNasab** [frrahat/Quran-For-My-Android#9]
Please add a feature for selecting a part of texts and copy them .
standard text selecting is good .

**Comment by frrahat** [comment]
Assalamu 'Alaikum, brother.
Here is a new release with text copying feature :https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.4.0

Please inform, if you find any bug.

**Comment by HassanHeydariNasab** [comment]
I find a bug at this feature . when I press the plus sign and enter an invalid format of Verse:Ayah , instead of showing an error or help ( similar to the main page ) it gets force close .

**Comment by frrahat** [comment]
Jazakallahu khairan, brother.
I will fix this and let you know about the update, insha Allah.

**Comment by frrahat** [comment]
Assalamu 'Aalaikum, brother.
Here is a new update: https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.4.1
